### ISSUE TITLE
Σαφέστερες οδηγίες για το που θα πρέπει να τοποθετηθούν τα αρχεία

### ISSUE THREAD

**Issue by johnnyxid** [eellak/epinoo-moodle-customisation#1]
Θα πρέπει να δωθούν σαφέστερες οδηγίες για το που θα πρέπει να τοποθετηθούν τα αρχεία γιατί αν κάποιος δεν έχει κάνει χρήση του moodle θα χρειαστεί αρκετό χρόνο να τα βρει.

Ας γραφτούν απλά τα paths που θα τοποθετηθούν

**Comment by vchatzigiannakis** [comment]
Έγιναν οι διορθώσεις
